--<ScriptOptions statementTerminator=";"/>

CREATE TABLE `activemq`.`activemq_acks` (
	`CONTAINER` VARCHAR(250) NOT NULL,
	`SUB_DEST` VARCHAR(250),
	`CLIENT_ID` VARCHAR(250) NOT NULL,
	`SUB_NAME` VARCHAR(250) NOT NULL,
	`SELECTOR` VARCHAR(250),
	`LAST_ACKED_ID` BIGINT,
	`PRIORITY` BIGINT DEFAULT 5 NOT NULL,
	`XID` VARCHAR(250),
	PRIMARY KEY (`CONTAINER`,`CLIENT_ID`,`SUB_NAME`,`PRIORITY`)
) ENGINE=InnoDB;

CREATE TABLE `activemq`.`activemq_lock` (
	`ID` BIGINT NOT NULL,
	`TIME` BIGINT,
	`BROKER_NAME` VARCHAR(250),
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `activemq`.`activemq_msgs` (
	`ID` BIGINT NOT NULL,
	`CONTAINER` VARCHAR(250),
	`MSGID_PROD` VARCHAR(250),
	`MSGID_SEQ` BIGINT,
	`EXPIRATION` BIGINT,
	`MSG` null,
	`PRIORITY` BIGINT,
	`XID` VARCHAR(250),
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE INDEX `ACTIVEMQ_MSGS_EIDX` ON `activemq`.`activemq_msgs` (`EXPIRATION` ASC);

CREATE INDEX `ACTIVEMQ_MSGS_MIDX` ON `activemq`.`activemq_msgs` (`MSGID_PROD` ASC);

CREATE INDEX `ACTIVEMQ_ACKS_XIDX` ON `activemq`.`activemq_acks` (`XID` ASC);

CREATE INDEX `ACTIVEMQ_MSGS_MIDX` ON `activemq`.`activemq_msgs` (`MSGID_SEQ` ASC);

CREATE INDEX `ACTIVEMQ_MSGS_CIDX` ON `activemq`.`activemq_msgs` (`CONTAINER` ASC);

CREATE INDEX `ACTIVEMQ_MSGS_XIDX` ON `activemq`.`activemq_msgs` (`XID` ASC);

CREATE INDEX `ACTIVEMQ_MSGS_PIDX` ON `activemq`.`activemq_msgs` (`PRIORITY` ASC);

