CREATE TABLE PLMT.PLMATTRIBUTEMAPPING (
	PLM1_TYPE_ID VARCHAR(100) NOT NULL,
	PLM1_TYPE_NAME VARCHAR(100),
	PLM1_NAME VARCHAR(100) NOT NULL,
	PLM1_ATTRIBUTE_ID VARCHAR(100) NOT NULL,
	PLM1_ATTRIBUTE_NAME VARCHAR(100),
	PLM2_TYPE_ID VARCHAR(100) NOT NULL,
	PLM2_TYPE_NAME VARCHAR(100),
	PLM2_NAME VARCHAR(100) NOT NULL,
	PLM2_ATTRIBUTE_ID VARCHAR(100) NOT NULL,
	PLM2_ATTRIBUTE_NAME VARCHAR(100),	
	"ID" INTEGER primary key NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1)
);
