INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type123', 'Type123', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');

INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type33', 'Type33', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');


INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type13', 'Type13', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');

INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type23', 'Type23', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');


INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type223', 'Type223', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');

INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type2', 'Type2', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');

INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type5', 'Type5', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');

INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type3', 'Type3', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');

INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('Type4', 'Type4', 'Windchill', 'Attr2', 'Attr2', 'Type3', 'Type3', 'Attr2', 'Attr2', 'Team Center');