
INSERT INTO PLMT.PLMATTRIBUTEMAPPING
(PLM1_TYPE_ID, PLM1_TYPE_NAME, PLM1_NAME, PLM1_ATTRIBUTE_ID, PLM1_ATTRIBUTE_NAME, PLM2_TYPE_ID, PLM2_TYPE_NAME, PLM2_NAME, PLM2_ATTRIBUTE_ID, PLM2_ATTRIBUTE_NAME)
VALUES('wt.doc.WTDocument', 'wt.doc.WTDocument', 'Windchill', 'name', 'name', 'Document', 'Document', 'Enovia', 'name', 'name');
