CREATE TABLE PLMT.PLMATTRIBUTELIST (
	ATTRIBUTE_ID VARCHAR(100),
	ATTRIBUTE_NAME VARCHAR(100),
	PLM_NAME VARCHAR(100),
	"ID" INTEGER primary key NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1)
);
