--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "PLMT"."COMPLETEDJOBS" DROP CONSTRAINT "COMPLETEDJOBS_QUEUE_FK";

ALTER TABLE "PLMT"."FAILEDJOBS" DROP CONSTRAINT "FAILEDJOBS_QUEUE_FK";

ALTER TABLE "PLMT"."COMPLETEDJOBS" DROP CONSTRAINT "SQL141223130321450";

ALTER TABLE "PLMT"."QUEUE" DROP CONSTRAINT "SQL141223130321350";

ALTER TABLE "PLMT"."FAILEDJOBS" DROP CONSTRAINT "SQL141223130321530";

DROP INDEX "PLMT"."FAILEDJOBS_MIDSEQX";

DROP INDEX "PLMT"."COMPLETEDJOBS_EIDX";

DROP INDEX "PLMT"."SQL141223130326710";

DROP INDEX "PLMT"."SQL141223130321350";

DROP INDEX "PLMT"."FAILEDJOBS_CIDX";

DROP INDEX "PLMT"."COMPLETEDJOBS_MIDSEQX";

DROP INDEX "PLMT"."FAILEDJOBS_EIDX";

DROP INDEX "PLMT"."SQL141223130321531";

DROP INDEX "PLMT"."QUEUE_CIDX";

DROP INDEX "PLMT"."COMPLETEDJOBS_XIDX";

DROP INDEX "PLMT"."QUEUE_XIDX";

DROP INDEX "PLMT"."SQL141223130321450";

DROP INDEX "PLMT"."COMPLETEDJOBS_CIDX";

DROP INDEX "PLMT"."SQL141223130321530";

DROP INDEX "PLMT"."QUEUE_PIDX";

DROP INDEX "PLMT"."COMPLETEDJOBS_MIDPRODX";

DROP INDEX "PLMT"."FAILEDJOBS_XIDX";

DROP INDEX "PLMT"."SQL141223130326700";

DROP INDEX "PLMT"."COMPLETEDJOBS_PIDX";

DROP INDEX "PLMT"."QUEUE_MIDSEQX";

DROP INDEX "PLMT"."QUEUE_MIDPRODX";

DROP INDEX "PLMT"."FAILEDJOBS_PIDX";

DROP INDEX "PLMT"."SQL141223130321451";

DROP INDEX "PLMT"."QUEUE_EIDX";

DROP INDEX "PLMT"."FAILEDJOBS_MIDPRODX";

DROP TABLE "PLMT"."QUEUE";

DROP TABLE "PLMT"."COMPLETEDJOBS";

DROP TABLE "PLMT"."FAILEDJOBS";

CREATE TABLE "PLMT"."QUEUE" (
		"CONTAINER" VARCHAR(250),
		"MSGID_PROD" VARCHAR(250),
		"MSGID_SEQ" BIGINT,
		"EXPIRATION" BIGINT,
		"PRIORITY" BIGINT,
		"XID" VARCHAR(250),
		"MSG" BLOB(2147483647),
		"MSG_ID" VARCHAR(100) NOT NULL,
		"QUEUE_ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"CREATED_DATE" TIMESTAMP,
		"PROCESS_DATE" TIMESTAMP
	);

CREATE TABLE "PLMT"."COMPLETEDJOBS" (
		"CONTAINER" VARCHAR(250),
		"MSGID_PROD" VARCHAR(250),
		"MSGID_SEQ" BIGINT,
		"EXPIRATION" BIGINT,
		"MSG" BLOB(2147483647),
		"PRIORITY" BIGINT,
		"XID" VARCHAR(250),
		"COMPLETED_ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"QUEUE_ID" INTEGER NOT NULL,
		"COMPLETED_DATE" TIMESTAMP,
		"CREATED_DATE" TIMESTAMP
	);

CREATE TABLE "PLMT"."FAILEDJOBS" (
		"CONTAINER" VARCHAR(250),
		"MSGID_PROD" VARCHAR(250),
		"MSGID_SEQ" BIGINT,
		"EXPIRATION" BIGINT,
		"MSG" BLOB(2147483647),
		"PRIORITY" BIGINT,
		"XID" VARCHAR(250),
		"FAILED_ID" INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"QUEUE_ID" INTEGER NOT NULL,
		"CREATED_DATE" TIMESTAMP,
		"FAILED_DATE" TIMESTAMP
	);

CREATE INDEX "PLMT"."FAILEDJOBS_MIDSEQX" ON "PLMT"."FAILEDJOBS" ("MSGID_SEQ" ASC);

CREATE INDEX "PLMT"."COMPLETEDJOBS_EIDX" ON "PLMT"."COMPLETEDJOBS" ("EXPIRATION" ASC);

CREATE INDEX "PLMT"."SQL141223130326710" ON "PLMT"."COMPLETEDJOBS" ("QUEUE_ID" ASC);

CREATE UNIQUE INDEX "PLMT"."SQL141223130321350" ON "PLMT"."QUEUE" ("QUEUE_ID" ASC);

CREATE INDEX "PLMT"."FAILEDJOBS_CIDX" ON "PLMT"."FAILEDJOBS" ("CONTAINER" ASC);

CREATE INDEX "PLMT"."COMPLETEDJOBS_MIDSEQX" ON "PLMT"."COMPLETEDJOBS" ("MSGID_SEQ" ASC);

CREATE INDEX "PLMT"."FAILEDJOBS_EIDX" ON "PLMT"."FAILEDJOBS" ("EXPIRATION" ASC);

CREATE UNIQUE INDEX "PLMT"."SQL141223130321531" ON "PLMT"."FAILEDJOBS" ("QUEUE_ID" ASC);

CREATE INDEX "PLMT"."QUEUE_CIDX" ON "PLMT"."QUEUE" ("CONTAINER" ASC);

CREATE INDEX "PLMT"."COMPLETEDJOBS_XIDX" ON "PLMT"."COMPLETEDJOBS" ("XID" ASC);

CREATE INDEX "PLMT"."QUEUE_XIDX" ON "PLMT"."QUEUE" ("XID" ASC);

CREATE UNIQUE INDEX "PLMT"."SQL141223130321450" ON "PLMT"."COMPLETEDJOBS" ("COMPLETED_ID" ASC);

CREATE INDEX "PLMT"."COMPLETEDJOBS_CIDX" ON "PLMT"."COMPLETEDJOBS" ("CONTAINER" ASC);

CREATE UNIQUE INDEX "PLMT"."SQL141223130321530" ON "PLMT"."FAILEDJOBS" ("FAILED_ID" ASC);

CREATE INDEX "PLMT"."QUEUE_PIDX" ON "PLMT"."QUEUE" ("PRIORITY" ASC);

CREATE INDEX "PLMT"."COMPLETEDJOBS_MIDPRODX" ON "PLMT"."COMPLETEDJOBS" ("MSGID_PROD" ASC);

CREATE INDEX "PLMT"."FAILEDJOBS_XIDX" ON "PLMT"."FAILEDJOBS" ("XID" ASC);

CREATE INDEX "PLMT"."SQL141223130326700" ON "PLMT"."FAILEDJOBS" ("QUEUE_ID" ASC);

CREATE INDEX "PLMT"."COMPLETEDJOBS_PIDX" ON "PLMT"."COMPLETEDJOBS" ("PRIORITY" ASC);

CREATE INDEX "PLMT"."QUEUE_MIDSEQX" ON "PLMT"."QUEUE" ("MSGID_SEQ" ASC);

CREATE INDEX "PLMT"."QUEUE_MIDPRODX" ON "PLMT"."QUEUE" ("MSGID_PROD" ASC);

CREATE INDEX "PLMT"."FAILEDJOBS_PIDX" ON "PLMT"."FAILEDJOBS" ("PRIORITY" ASC);

CREATE UNIQUE INDEX "PLMT"."SQL141223130321451" ON "PLMT"."COMPLETEDJOBS" ("QUEUE_ID" ASC);

CREATE INDEX "PLMT"."QUEUE_EIDX" ON "PLMT"."QUEUE" ("EXPIRATION" ASC);

CREATE INDEX "PLMT"."FAILEDJOBS_MIDPRODX" ON "PLMT"."FAILEDJOBS" ("MSGID_PROD" ASC);

ALTER TABLE "PLMT"."COMPLETEDJOBS" ADD CONSTRAINT "SQL141223130321450" PRIMARY KEY ("COMPLETED_ID");

ALTER TABLE "PLMT"."QUEUE" ADD CONSTRAINT "SQL141223130321350" PRIMARY KEY ("QUEUE_ID");

ALTER TABLE "PLMT"."FAILEDJOBS" ADD CONSTRAINT "SQL141223130321530" PRIMARY KEY ("FAILED_ID");

ALTER TABLE "PLMT"."COMPLETEDJOBS" ADD CONSTRAINT "COMPLETEDJOBS_QUEUE_FK" FOREIGN KEY ("QUEUE_ID")
	REFERENCES "PLMT"."QUEUE" ("QUEUE_ID")
	ON DELETE CASCADE;

ALTER TABLE "PLMT"."FAILEDJOBS" ADD CONSTRAINT "FAILEDJOBS_QUEUE_FK" FOREIGN KEY ("QUEUE_ID")
	REFERENCES "PLMT"."QUEUE" ("QUEUE_ID")
	ON DELETE CASCADE;

