CREATE TABLE PLMT.PLMTYPELIST (
	TYPE_ID VARCHAR(100),
	TYPE_NAME VARCHAR(100),
	PLM_NAME VARCHAR(100),
	"ID" INTEGER primary key NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1)
);
